dist: trusty
language: node_js
node_js:
- '6'
before_script:
- npm install -g bower web-component-tester
- bower install
script: xvfb-run wct
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable